package:
   name: intake-asammdf
   version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - jinja2
  run:
    - python
    - intake
    - sqlalchemy
    - pandas

test:
  source_files:
    - tests
  requires:
    - coverage
    - ibis-framework
    - sqlalchemy<1.3.7
    - pytest
    - pytest-cov
  commands:
    - py.test --verbose --cov=intake_asammdf tests

about:
  home: https://github.com/AutomotiveDevOps/intake-asammdf
  license: BSD
  license_file: LICENSE
  summary: |
    sql plugin for Intake
